#!/bin/sh
FILE=commit.cmd
if test -f "$FILE"; then
    echo "$FILE exists."
    rm commit.cmd
    exit 0;
fi

case `uname` in
    *CYGWIN*|*MINGW*|*MSYS*)
        echo "npx cz && exit" > commit.cmd
        start commit.cmd
    exit 1;;
esac

. "$(dirname "$0")/_/husky.sh"

exec </dev/tty && node_modules/.bin/cz --hook || true
